"""
Module for Session class to represent and manipulate a current user's login session.
"""

from csv import DictReader


#######################
#    Session Class    #
#######################

class Session():
    """
    A class to manage the current login session.
    """

    #####################
    #    Constructor    #
    #####################

    def __init__(self, username: str, pwHash: bytes):
        """
        Creates a new Session object.
        Parameters:
            `username`: The username for the current user.
            `pwHash`: The current user's password hash as bytes.
        """

        #init

        self.username = username
        self.pwHash = pwHash


    #################
    #    Methods    #
    #################

    def addPassword(self, pwName: str, password: str):
        """
        Adds a new password entry to the current user's password list.
        Parameters:
            `pwName`: A name to associate with the new password.
            `password`: The plaintext password.
        """

        pass

    def _loadPasswords(self) -> list:
        """
        Loads the current user's passwords from their file.
        Returns:
            A list of every row in the password file as generated by csv.DictReader.
        """

        pass

    def _generatePasswordFile(self):
        """
        Generates a new password file for the current user if it doesn't exist.
        """

        pass